<?php return array (
  'trans' => 
  array (
    'Login Page' => 
    array (
      'Username' => 'Uživatelské jméno',
      'Password' => 'Heslo',
      'Language' => 'Jazyk',
      'Sign in' => 'Přihlásit',
      'Please login.' => 'Prosím přihlašte se.',
      'Please type a username.' => 'Zadejte prosím uživatelské jméno.',
      'Invalid password.' => 'Chybné heslo.',
      'Invalid username.' => 'Chybné uživatelské jméno.',
      'Your account has been deactivated!' => 'Váš účet byl deaktivován!',
      'Create account' => 'Vytvořit účet',
      'Forgot password?' => 'Zapomenuté heslo?',
      'Signing in...' => 'Přihlašuji...',
      '2-step verification: add account' => '2 kroková verifikace: přidat účet',
      'Scan this barcode with the <a href="%1" target="_blank">Google Authenticator</a> app on your mobile device to add your account.' => 'Naskenujte tento čárový kód pomocí aplikace <a href="%1" target="_blank">Google Authenticator</a> ve vašem mobilním telefonu.',
      'Done' => 'Hotovo',
      'Your account is configured for 2-step verification. You need to type in a verification code!' => 'Váš účet je nastaven pro 2-fázové přihlašování. Musíte zadat ověřovací kód!',
      'The provided verification code is not valid!' => 'Zadaný verifikační kód je neplatný!',
      'Your account is configured for 2-step verification. Click Ok to start the setup.' => 'Váš účet je nastaven na 2-fázové přihlašování. Klikněte na OK pro nastavení.',
      'Type the following key code into your authentication app:' => 'Zadejte následující klíč do aplikace Google Autheticator.',
    ),
    'User Registration' => 
    array (
      'User Registration' => 'Registrace uživatele',
      'Username' => 'Uživatelské jméno',
      'E-mail address' => 'E-mailová adresa',
      'Password' => 'Heslo',
      'Retype password' => 'Heslo znovu',
      'Name' => 'Jméno',
      'Company' => 'Společnost',
      'Web site address' => 'Webová stránka',
      'Comment' => 'Komentář',
      'Submit' => 'Potvrdit',
      'Please type a username!' => 'Prosím vyplňte uživatelské jméno!',
      'Please avoid using special characters for the username!' => 'Nepoužívejte nepovolené znaky v uživatelském jménu!',
      'Username already in use. Please choose another one.' => 'Toto uživatelské jméno je již registrováno. Prosím vyberte jiné.',
      'Please type a password!' => 'Prosím vyplňte heslo!',
      'Please retype the password correctly!' => 'Hesla se neshodují!',
      'Please type your name!' => 'Prosím vyplňte Vaše jméno!',
      'Please type your email address!' => 'Prosím vyplňte Vaši e-mailovou adresu!',
      'Please type the company name!' => 'Prosím vyplňte název společnosti!',
      'Please type your website address!' => 'Prosím vyplňte adresu Vašich webových stránek!',
      'Please type the comment!' => 'Prosím vyplňte komentář!',
      'Failed to create user account!' => 'Chyba při vytváření uživatelského účtu!',
      'Your account has been successfully created.' => 'Váš uživatelský účet byl úspěšně vytvořen.',
      'Your account information has been emailed to you!' => 'Přihlašovací údaje byly odeslány na Vaši e-mailovou adresu!',
      'An e-mail message has been sent at "%1" with details on how to complete the registration process.' => 'Na zadaný e-mail "%1" byly odeslány pokyny k dokončení registračního procesu.',
    ),
    'Main Interface' => 
    array (
      'Loading...' => 'Načítám...',
      'Sign out' => 'Odhlásit',
      'Control Panel' => 'Nastavení',
      'Change password' => 'Změnit heslo',
      'Preview' => 'Náhled',
      'No preview available for this type of files.' => 'Pro tento typ souboru není k dispozici náhled.',
      'Comments' => 'Komentáře',
      'Please select a file.' => 'Prosím vyberte soubor.',
      'Folder contains no image file' => 'Adresář je prázdný.',
      'There are no files in this folder' => 'V tomto adresáři nejsou žádné soubory.',
      'This item contains changes' => 'Tento soubor byl upraven od Vašeho posledního přístupu.',
      'This file is locked by %1.' => 'Tento soubor je uzamčen uživatelem %1.',
      'This file has %1 comment(s).' => 'K tomuto souboru je vloženo %1 komentářů.',
      'This file has a WebLink attached to it.' => 'Tento soubor je zpřístupněn na webu.',
      'Loading Preview...' => 'Načítám náhled...',
      'Free space available:' => 'Volné místo:',
      'Delete "%1"?' => 'Potvrzení',
      'Internet Explorer is blocking the download?<br>Click <a href="%1" target="_blank">here</a> to download the file without reloading this page.' => 'Blokuje Internet Explorer stažení souboru?<br>Klikněte <a href="%1" target="_blank">zde</a> a stáhněte soubor bez obnovování této stránky.',
      'Upload' => 'Nahrát',
      'Please type a file name:' => 'Napište prosím jméno souboru:',
      'Creating blank file...' => 'Vytvářím prázdný soubor...',
      'Select All' => 'Vybrat vše',
      'View' => 'Prohlédnout',
      'Tools' => 'Nástroje',
      'List view' => 'Detailní zobrazení',
      'Refresh' => 'Obnovit',
      'New File' => 'Soubor',
      'New tab' => 'Nové záložce',
      'Space:' => 'Místo:',
      'Search' => 'Hledat',
      'File Search' => 'Hledání souborů',
      'Share' => 'Sdílet',
      'Sharing' => 'Sdílení',
      'New sub-folder' => 'Nový podadresář',
      'Rename' => 'Přejmenovat',
      'Remove' => 'Smazat',
      'Properties' => 'Vlastnosti',
      'Download' => 'Stáhnout',
      '..in one zip file' => '..jako jeden zip soubor',
      'Open with..' => 'Otevřít v..',
      'E-mail Files' => 'Odeslat e-mailem',
      'Get link' => 'Odkaz na web',
      'Details and activity' => 'Oznámení',
      'Versioning' => 'Verzování',
      'Previous Versions' => 'Předchozí verze',
      'Lock' => 'Zamknout',
      'Unlock' => 'Odemknout',
      'File Versions' => 'Verze souboru',
      'Comment' => 'Komentář',
      'Zip archive..' => 'Přidat do zipu',
      'Extract archive..' => 'Rozbalit',
      'Copy' => 'Kopírovat',
      'Loading file list...' => 'Načítám seznam souborů...',
      'Name' => 'Jméno',
      'Size' => 'Velikost',
      'Type' => 'Typ',
      'Meta Type' => 'Meta Typ',
      'Modified' => 'Datum změny',
      'Created' => 'Datum vytvoření',
      'Comments count' => 'Počet komentářů',
      'Yes' => 'Ano',
      'No' => 'Ne',
      'Version' => 'Verze',
      'Locked by' => 'Zamčeno uživatelem',
      'Sort Ascending' => 'Řadit vzestupně',
      'Sort Descending' => 'Řadit sestupně',
      'Columns' => 'Sloupce',
      'Reset Columns' => 'Původní sloupce',
      '%1 items' => '%1 souborů',
      'Opening popup window... <br>Click <a href="%1" target="_blank">here</a> if the browser prevents it from opening.' => 'Otevírám popup okno... <br>Klikněte <a href="%1" target="_blank">zde</a>, pokud prohlížeč blokuje jeho otevření.',
      'Moving files...' => 'Přesouvám soubory...',
      'Moving folder...' => 'Přesouvám adresář...',
      'Renaming file...' => 'Přejmenovávám soubor...',
      'Zipping files...' => 'Komprimuji soubory...',
      'Extracting archive contents...' => 'Rozbaluji soubory...',
      'Deleting...' => 'Mažu soubory...',
      'Restoring file(s)...' => 'Obnovuji soubory...',
      'Locking file...' => 'Zamykám soubor...',
      'Unlocking file...' => 'Odemykám soubor...',
      'Renaming folder...' => 'Přejmenovávám adresář...',
      'Please wait while the selected files are being zipped...' => 'Prosím počkejte, než budou vybrané soubory zkomprimovány...',
      'Please wait while the selected folder is being zipped...' => 'Prosím počkejte, než bude vybraný adresář zkomprimován...',
      'Selected Files.zip' => 'Vybrané Soubory.zip',
      'Downloading zip file...' => 'Stahuji zip soubor...',
      'Are you sure you want to delete the selected file(s)?' => 'Opravdu chcete smazat vybrané soubory?',
      'The selected folder and all its contents will be deleted.' => 'Opravdu chcete smazat vybraný adresář a veškerý jeho obsah?',
      'Permanent deletion' => 'Trvalé smazání',
      'New Folder' => 'Nový adresář',
      'Creating new folder...' => 'Vytvářím nový adresář...',
      'Please type a folder name for the archive contents:' => 'Jméno zkomprimovaného adresáře:',
      'Extracted Files' => 'Rozbalené soubory',
      'Deleted from' => 'Smazáno z',
      'Trash' => 'Smazané soubory',
      'Restore' => 'Obnovit',
      'Please type a name for the zip file:' => 'Jméno zip souboru:',
      'New Archive.zip' => 'Nový archiv.zip',
    ),
    'General' => 
    array (
      'Submit' => 'Potvrdit',
      'Save' => 'Uložit',
      'Cancel' => 'Zrušit',
      'Error' => 'Chyba',
      'Invalid path.' => 'Neplatná cesta.',
      'File not found!' => 'Soubor nenalezen!',
      'You are not allowed to preview the selected file.' => 'Nemáte oprávnění pro zobrazení náhledu vybraného souboru.',
      '%1 users' => '%1 uživatelů',
      'You are not allowed to download the requested file!' => 'Nemáte oprávnění ke stažení požadovaného souboru!',
      'The file you are trying to download is no longer available!' => 'Soubor, který se pokoušíte stáhnout, není již k dispozici!',
      'You are not allowed to download or preview files.' => 'Nemáte oprávnění stahovat nebo zobrazovat náhled souborů.',
      'Invalid folder.' => 'Neplatný adresář.',
      'You are not allowed to copy that shared file.' => 'Nemáte oprávnění kopírovat tento sdílený soubor.',
      'You are not allowed to copy files to the specified target.' => 'Nemáte oprávnění kopírovat soubory do tohoto cíle.',
      'No file was copied!' => 'Nebyly zkopírovány žádné soubory!',
      'One file copied.' => 'Jeden soubor zkopírován.',
      '%1 files copied.' => '%1 souborů zkopírováno.',
      'No more file space available.' => 'Není volné místo na disku.',
      'You are not allowed to delete files from this shared folder.' => 'Nemáte oprávnění mazat soubory z tohoto sdíleného adresáře.',
      'No files were deleted!' => 'Nebyl smazán žádný soubor!',
      'One file deleted.' => 'Jeden soubor smazán.',
      '%1 files successfully deleted.' => '%1 souborů smazáno.',
      'You are not allowed to move that shared file.' => 'Nemáte oprávnění přeunout tento sdílený soubor.',
      'You are not allowed to move files to the specified target.' => 'Nemáte oprávnění přesouvat soubory do tohoto cíle.',
      'You are not allowed to move these shared files to your own folder.' => 'Nemáte oprávnění přesouvat soubory do Vašeho adresáře.',
      'No file was moved!' => 'Nebyl přesunut žádný soubor!',
      'One file moved.' => 'Jeden soubor přesunut.',
      '%1 files moved.' => '%1 souborů přesunuto.',
      'Invalid target path, file already exists.' => 'Neplatná cílová cesta, soubor již existuje.',
      'The selected file is currently locked by another user.' => 'Soubor je uzamčen někým jiným.',
      'Invalid path, not a file.' => 'Neplatná cesta, toto není soubor.',
      'Invalid path, not a folder.' => 'Neplatná cesta, toto není adresář.',
      'Invalid source path, not a folder.' => 'Neplatná zdrojová cesta, toto není adresář.',
      'Invalid target path, not a folder.' => 'Neplatná cílová cesta, toto není adresář.',
      'Invalid source path, not a file.' => 'Neplatná zdrojová cesta, toto není soubor.',
      'You are not allowed to rename files in this shared folder.' => 'Nemáte oprávnění přejmenovávat soubory v tomto sdíleném adresáři.',
      'File successfully renamed.' => 'Soubor úspěšně přejmenován.',
      'There is already a file or a folder with the same name!' => 'Soubor s tímto názvem již v adresáři existuje!',
      'Failed to rename file!' => 'Chyba při přejmenovávání souboru!',
      'You are not allowed to extract archives in this shared folder.' => 'Nemáte oprávnění rozbalovat soubory v tomto sdíleném adresáři.',
      'You are not allowed to zip files in this shared folder.' => 'Nemáte oprávnění komprimovat soubory v tomto sdíleném adresáři.',
      'Invalid folder name!' => 'Neplatné jméno adresáře!',
      'Invalid file name' => 'Neplatné jméno souboru',
      'A folder with that name already exists!' => 'Adresář s tímto názvem již existuje!',
      'Unzipped Files' => 'Rozbalené soubory',
      'The archive was successfully extracted.' => 'Archiv byl úspěšně rozbalen.',
      'Invalid zip name!' => 'Neplatné zip jméno!',
      'A file with that name already exists!' => 'Soubor s tímto jménem již existuje!',
      'Zip archive successfully created.' => 'Zip archiv byl úspěšně vytvořen.',
      'You are not allowed to delete that shared folder.' => 'Nemáte oprávnění smazat tento sdílený adresář.',
      'You cannot delete the root of a shared folder.' => 'Nemůžete smazat hlavní ze sdílených adresářů.',
      'Folder deleted.' => 'Adresář smazán.',
      'Failed to delete folder!' => 'Chyba při mazání adresáře!',
      'You are not allowed to move that shared folder.' => 'Nemáte oprávnění přesunout tento sdílený adresář.',
      'You are not allowed to copy that shared folder.' => 'Nemáte oprávnění kopírovat tento sdílený adresář.',
      'You are not allowed to copy folder to the specified target.' => 'Nemáte oprávnění kopírovat adresář do zvoleného cíle.',
      'You are not allowed to move the folder to the shared location.' => 'Nemáte oprávěnní přesunout adresář do sdíleného umístění.',
      'You are not allowed to move this shared folder to your own folder.' => 'Nemáte oprávnění přesunout tento sdílený adresář do Vašeho adresáře.',
      'Folder moved.' => 'Adresář byl přesunut.',
      'Failed to move folder!' => 'Chyba při přesunu adresáře!',
      'Failed to rename folder!' => 'Chyba při přejmenovávání adresáře!',
      'There is already a folder with the same name in this folder!' => 'Adresář s tímto názvem již v cílovém adresáři existuje!',
      'Folder successfully created.' => 'Adresář byl vytvořen.',
      'Failed to upload file "%1": %2' => 'Chyba při nahrávání souboru "%1": %2',
      'You are not allowed to upload to this shared folder.' => 'Nemáte oprávnění nahrávat soubory do tohoto sdíleného adresáře.',
      'No more file space available!' => 'Není volné místo pro soubory!',
      'File uploaded.' => 'Soubor byl nahrán.',
      'The previous version is available from the versioning menu.' => 'Předchozí verze je dostupná z menu verzování.',
      'Failed to upload file.' => 'Chyba při nahrávání souboru.',
      'Please specify a file for upload.' => 'Prosím vyberte soubor k nahrání.',
      'The monthly traffic limit has been reached!' => 'Bylo dosaženo měsíčního limitu přenosu dat!',
      'Click <a href="%1">here</a> to go back.' => 'Klikněte <a href="%1">zde</a> pro návrat.',
      'A file named "%1" already exists!' => 'Soubor "%1" již existuje!',
      'The path of your home folder doesn\'t point to an existing folder. Please contact the site administrator.' => 'Cesta k Vašemu domovskému adresáři není platná. Kontaktujte prosím administrátora.',
      'Zip Archive.zip' => 'Zip Archiv.zip',
      'The shared folder is no longer available.' => 'Sdílený adresář není již dostupný.',
      'You are not allowed to modify files in this shared folder.' => 'Nemáte oprávnění měnit soubory v tomto sdíleném adresáři.',
    ),
    'Trash' => 
    array (
      'A file or folder already exists at the original location.' => 'Koš: obnovený soubor již existuje.',
      'No items were restored!' => 'Nebyly obnoveny žádné položky!',
      'One item restored.' => 'Jedna položka obnovena.',
      '%1 items successfully restored.' => '%1 položek úspěšně obnoveno.',
    ),
    'Account Settings' => 
    array (
      'Current password' => 'Současné heslo',
      'New password' => 'Nové heslo',
      'Confirm new password' => 'Nové heslo znovu',
      'Save changes' => 'Uložit',
      'Cancel' => 'Zrušit',
      'Please type the current password correctly.' => 'Chybné původní heslo.',
      'Please retype the new password correctly.' => 'Hesla se neshodují.',
    ),
    'E-mail Files' => 
    array (
      'Please fill in "From" field!' => 'Prosím vyplňte pole "od"',
      'Please set at least one recipient!' => 'Prosím vyplňte pole "komu"',
      'Please type a subject!' => 'Prosím vyplňte předmět!',
      'Please type a message!' => 'Prosím vyplňte zprávu!',
      'Email successfuly sent!' => 'E-mail byl úspěšně odeslán!',
      'Failed to send email!' => 'Chyba při odesílání e-mailu!',
      'From' => 'Od',
      'To' => 'Komu',
      'Separate recipients by ,' => 'Oddělit příjemce čárkou ,',
      'Select Users' => 'Vybrat uživatele',
      'Cancel' => 'Zrušit',
      'Subject' => 'Předmět',
      'Message' => 'Zpráva',
      'Attachments' => 'Přílohy',
      'Send WebLinks instead of attaching the files.' => 'Odeslat webové odkazy místo zasílání souborů.',
      'Web link to' => 'Webový odkaz komu',
      'Send' => 'Odeslat',
      'Please make the appropriate <br>changes to the highlighted fields.' => 'Prosím vhodně upravte <br>zvýrazněné položky',
      'Sending e-mail...' => 'Odesílám e-mail, prosím počkejte...',
      'No recipient addresses found!' => 'Nebyla nalezena žádná adresa příjemce!',
      'You are not allowed to share the file "%1"!' => 'Nemáte oprávnění posílat e-mailem soubory z tohoto adresáře!',
      'Web Link Options' => 'Nastavení webového odkazu',
    ),
    'Share Files' => 
    array (
      'Upload' => 'Nahrát',
      'Add comments' => 'Přidat komentáře',
      'Read comments' => 'Číst komentáře',
      'Share anonymously' => 'Sdílet anonymně',
      'Share with' => 'Sdílet s',
      'Select Users' => 'Vybrat uživatele',
      'Cancel' => 'Zrušit',
      'Unsorted, %1 users' => 'Neseřazeno, %1 uživatelů',
      'Permissions' => 'Oprávnění',
      'Options' => 'Nastavení',
      'Add Users' => 'Přidat uživatele',
      'Save' => 'Uložit',
      'Loading data...' => 'Načítám data...',
      'Saving options...' => 'Ukládám nastavení...',
      'Add users to share with.' => 'Uživatelé, se kterými je sdíleno.',
      'Sharing options saved.' => 'Nastavení sdílení uloženo.',
    ),
    'Folder Notifications' => 
    array (
      'Notification settings successfully saved' => 'Nastavení oznámení bylo úspěšně uloženo',
    ),
    'Web Links' => 
    array (
      'Loading data...' => 'Načítám data...',
      'Link address' => 'Adresa odkazu',
      'Expiration date' => 'Datum expirace',
      'Download limit' => 'Limit stažení',
      'Set a password' => 'Nastavit heslo',
      'Receive e-mail notifications.' => 'Přijímat oznámení na e-mail',
      'Allow visitors to upload files.' => 'Umožnit nahrávání souborů',
      'Save changes' => 'Změnit nastavení',
      'Remove link' => 'Odebrat webový odkaz',
      'You cannot allow uploads in this folder' => 'Nemůžete umožnit nahrávání souborů do tohoto adresáře',
      'Web link successfully created!' => 'Webový odkaz byl úspěšně vytvořen!',
      'Failed to create web link!' => 'Chyba při vytváření webového odkazu!',
      'Web link successfully updated!' => 'Webový odkaz byl úspěšně změněn!',
      'Failed to update web link!' => 'Chyba při změně webového odkazu!',
      'Web link successfully deleted!' => 'Webový odkaz byl úspěšně smazán!',
      'Failed to delete web link!' => 'Chyba při mazání webového odkazu!',
      'The requested file requires a password.' => 'Požadovaný soubor vyžaduje heslo.',
      'Password' => 'Heslo',
      'Submit' => 'Potvrdit',
      'The requested file is no longer available!' => 'Požadovaný soubor již není dostupný!',
      'Click <a href="%1">here</a> to go back.' => 'Klikněte <a href="%1">zde</a> pro návrat.',
    ),
    'Metadata' => 
    array (
      'You are not allowed to alter data in this shared folder.' => 'Nemáte oprávnění měnit data v tomto sdíleném adresáři.',
      'Software Error: Failed to insert new path.' => 'Chyba softwaru: nepodařilo se přidat novou cestu.',
      'File Type' => 'Typ souboru',
      'Select...' => 'Vyberte...',
      '- File Type Not Found -' => '- typ souboru nenalezen -',
      'Save' => 'Uložit',
      'Saving data...' => 'Ukládám data...',
      'Failed to save data!' => 'Chyba při ukládání dat!',
      '- No Special Type -' => '- žádný speciální typ -',
    ),
    'Versioning' => 
    array (
      'Version' => 'Verze',
      'User' => 'Uživatel',
      'Date' => 'Datum',
      'Download' => 'Stáhnout',
      'Restore' => 'Obnovit',
      'Delete' => 'Smazat',
      'File version restored.' => 'Verze souboru obnovena.',
      'Failed to restore file version.' => 'Chyba při obnově verze souboru.',
      'File version deleted.' => 'Verze souboru smazána.',
      'Failed to delete file version.' => 'Chyba při mazání verze souboru.',
      'You are not allowed to lock/unlock files in this shared folder.' => 'Nemáte oprávnění zamknout/odemknout soubory v tomto sdíleném adresáři.',
      'The file has been locked.' => 'Soubor byl uzamčen.',
      'The file has been unlocked.' => 'Soubor byl odemčen.',
      'Failed to lock file!' => 'Chyba při zamykání souboru!',
      'Failed to unlock file!' => 'Chyba při odemykání souboru!',
      'File is locked by another user.' => 'Soubor je uzamčen někým jiným.',
      'File is already locked by somebody else.' => 'Soubor je již uzamčen někým jiným.',
    ),
    'Searching' => 
    array (
      'File name' => 'Jméno souboru',
      'File contents' => 'Soubor obsahuje',
      'Look in' => 'Hledat v',
      'Metadata Field' => 'Pole Metadata',
      'Select...' => 'Vybrat...',
      'Path' => 'Cesta',
      'Searching...' => 'Hledám...',
      'Search' => 'Hledat',
      '- None Selected -' => '- nic nebylo vybráno -',
    ),
    'File Comments' => 
    array (
      'Author' => 'Autor',
      'Comment' => 'Komentář',
      'Add comment' => 'Přidat komentář',
      'Type in your comment' => 'Napište Váš komentář',
      'Remove comment' => 'Odebrat komentář',
      'You are not allowed to read comments.' => 'Nemáte oprávnění číst komentáře.',
      'You are not allowed to add comments.' => 'Nemáte oprávnění přidávat komentáře.',
      'You are not allowed to remove comments.' => 'Nemáte oprávnění mazat komentáře.',
      'You are not allowed to add comments to files in this shared folder.' => 'Nemáte oprávnění přidávat komentáře k souborům v tomto sdíleném adresáři.',
      'You are not allowed to remove comments from files in this shared folder.' => 'Nemáte oprávnění mazat komentáře u souborů v tomto sdíleném adresáři.',
      'You are allowed to delete only your own comments from a shared file.' => 'Můžete mazat pouze Vaše vlastní komentáře.',
      'You are not allowed to read comments in this shared folder.' => 'Nemáte oprávnění číst komentáře v tomto sdíleném adresáři.',
      'No comments available for this file.' => 'Nejsou vloženy žádné komentáře.',
      'Comment successfully added.' => 'Komentář byl úspěšně přidán.',
      'Failed to add comment to file.' => 'Chyba při přidávání komentáře k souboru.',
      'Comment successfully removed.' => 'Komentář úspěšně smazán.',
      'Failed to remove comment from file.' => 'Chyba při mazání komentáře u souboru.',
    ),
    'Admin: Users' => 
    array (
      'Date Format: Registration date' => 'd M Y',
      'Date Format: Last login' => 'd.M.Y, H:i',
      'Date Format: Expiration date' => 'd.M.Y',
    ),
    'Admin: Logs' => 
    array (
      'Date Format: Grid - Date' => 'm/d/Y h:i A',
    ),
  ),
);