<?php return array (
  'trans' => 
  array (
    'Login Page' => 
    array (
      'Username' => '사용자명',
      'Password' => '비밀번호',
      'Language' => '언어',
      'Sign in' => '로그인',
      'Please login.' => '로그인해주세요.',
      'Please type a username.' => '사용자명을 입력해주세요.',
      'Invalid password.' => '비밀번호가 틀립니다.',
      'Invalid username.' => '사용자명이 틀립니다.',
      'Your account has been deactivated!' => '사용자의 계정이 비활성화되었습니다!',
      'Create account' => '계정 만들기',
      'Forgot password?' => '비밀번호를 잊으셨나요?',
      'Signing in...' => '로그인 중...',
      'Your account access is limited to a particular IP address!' => '계정 액세스가 특정 IP 주소로 제한됨!',
      '2-step verification: add account' => '2단계 인증: 계정을 추가합니다.',
      'Scan this barcode with the <a href="%1" target="_blank">Google Authenticator</a> app on your mobile device to add your account.' => '바코드를 스캔합니다. <a href="%1" target="_blank">Google Authenticator</a> 계정을 추가하기 위해 모바일 기기에 앱을 설치하세요.',
      'Done' => '완료',
      'Your account is configured for 2-step verification. You need to type in a verification code!' => '사용자 계정은 2단계 인증으로 구성되었습니다. 인증 코드를 입력해주세요!',
      'The provided verification code is not valid!' => '인증 코드가 올바르지 않습니다.',
      'Your account is configured for 2-step verification. Click Ok to start the setup.' => '사용자 계정의 2단계 인증을 구성할 수 있습니다. 확인을 눌러 시작하세요.',
      'Type the following key code into your authentication app:' => '인증 앱에 다음 키 코드를 입력합니다:',
      'Verification code' => '인증 코드',
      'Please type a password.' => '비밀번호가 틀렸습니다.',
      'Changing language...' => '언어 변경 중...',
      'Loading...' => '불러오는 중...',
      'There is an Android app that you can use to access your files more comfortably. Would you like to try that instead?' => 'Android 앱은 파일을 보다 편안하게 액세스하는 데 사용할 수 있습니다. 설치하겠습니까?',
      'Add a new <a href="%1" target="_blank">Google Authenticator</a> account with the following key:' => '새 < a href="%1" target="_blank>Google Authenticator</a>을 추가합니다. 계정은 다음 키로 합니다.',
      '2-step: Add account' => '2단계 - 계정 추가',
      'Authentication should be made with the remote system.' => '원격 시스템을 사용하여 인증을 수행해야 합니다.',
    ),
    'Password Reset' => 
    array (
      'The login information has been sent to your email address.' => '로그인 정보가 이메일 주소로 전송되었습니다.',
      'Password Reset' => '비밀번호 초기화',
      'E-mail address' => '이메일 주소',
      'Submit' => '보내기',
      'Please type the e-mail address.' => '이메일을 입력해주세요.',
      'The e-mail address was not found in the database.' => '데이터베이스에서 이메일 주소를 찾을 수 없습니다.',
      'Please check your inbox for information on how to reset your account\'s password.' => '계정 비밀번호를 재설정하는 방법에 대한 정보는 받은 메일을 확인하세요.',
      'Please wait...' => '잠시만 기다려주세요...',
      'Sign in' => '로그인',
    ),
    'Main Interface' => 
    array (
      'The file is already in the download cart' => '파일이 이미 다운로드 카트에 있습니다.',
      'Rating' => '평점',
      'Please check your network connection.' => '네트워크 연결을 확인하세요.',
      'Loading...' => '불러오는중...',
      'Sign out' => '로그아웃',
      'Control Panel' => '제어판',
      'Change password' => '비밀번호 변경',
      'Preview' => '미리 보기',
      'No preview available for this type of files.' => '이 파일 유형에 사용할 수 있는 미리 보기가 없습니다.',
      'Comments' => '코멘트',
      'Please select a file.' => '파일을 선택해주세요.',
      'Folder contains no image file' => '폴더에 이미지 파일이 없습니다',
      'There are no files in this folder' => '이 폴더에 파일이 없습니다',
      'This item contains changes' => '이 항목에 변경 사항이 포함되어 있습니다',
      'This file is locked by %1.' => '이 파일은 %1에 의해 잠겨 있습니다.',
      'This file has %1 comment(s).' => '이 파일에는 %1개의 코멘트가 있습니다.',
      'This file has a WebLink attached to it.' => '이 파일에는 웹링크가 첨부되어 있습니다.',
      'Loading Preview...' => '미리보기 불러오는중...',
      'Free space available:' => '사용 가능 공간:',
      'Delete "%1"?' => '"%1" 삭제하시겠습니까?',
      'Internet Explorer is blocking the download?<br>Click <a href="%1" target="_blank">here</a> to download the file without reloading this page.' => 'Internet Explorer가 다운로드를 차단하고 있습니까?<br>이 페이지를 다시 로드하지 않고 파일을 다운로드하려면 <a href="%1" target="_blank">여기</a>를 클릭하세요.',
      'Upload' => '업로드',
      '%1 used (%2%)' => '%1이(가) 사용 됨(%2%)',
      'Please type a file name:' => '파일명을 입력해주세요:',
      'Creating blank file...' => '빈 파일을 생성하고있습니다.',
      'Sort' => '정렬',
      'Settings' => '설정',
      'Select All' => '모두 선택',
      'View' => '보기',
      'Tools' => '도구',
      'List view' => '리스트 보기',
      'Refresh' => '새로고침',
      'New File' => '새로운 파일',
      'New tab' => '새로운 탭',
      'Space:' => '공간:',
      'Search' => '검색',
      'File Search' => '파일 검색',
      'Share' => '공유',
      'Sharing' => '공유 중',
      'New sub-folder' => '새로운 하위 폴더',
      'Rename' => '이름 바꾸기',
      'Remove' => '지우기',
      'Properties' => '속성',
      'Download' => '다운로드',
      'Share with users' => '사용자와 공유',
      'Get link' => '링크 얻기',
      'Details and activity' => '세부사항 및 활동',
      'Versioning' => '버전',
      'Previous Versions' => '이전 버전',
      'Lock' => '잠금',
      'Unlock' => '잠금 해제',
      'File Versions' => '파일 버전',
      'Metadata' => '메타데이터',
      'Comment' => '코멘트',
      'Zip archive..' => '압축하기...',
      'Extract archive..' => '압축 풀기..',
      'Copy' => '복사',
      'Loading file list...' => '파일 목록 불러오는중...',
      'Name' => '이름',
      'Size' => '크기',
      'Type' => '유형',
      'Meta Type' => '메타 유형',
      'Modified' => '수정',
      'Created' => '생성 됨',
      'Comments count' => '코멘트 수',
      'Yes' => '예',
      'No' => '아니오',
      'Version' => '버전',
      'Is new' => '새로운',
      'Locked by' => '잠금 사용자',
      'Sort Ascending' => '오름차순 정렬',
      'Sort Descending' => '내림차순 정렬',
      'Columns' => '칼럼',
      'Reset Columns' => '칼럼 초기화',
      '%1 items' => '%1 항목',
      'Moving files...' => '파일 이동중...',
      'Moving folder...' => '폴더 이동중...',
      'Renaming file...' => '이름 바꾸는 중...',
      'Zipping files...' => '파일 압축 중...',
      'Extracting archive contents...' => '아카이브 컨텐츠를 추출하는 중...',
      'Deleting...' => '삭제 중...',
      'Restoring file(s)...' => '파일을 복원하는 중...',
      'Locking file...' => '파일 잠그는 중...',
      'Unlocking file...' => '파일 잠금 해제 중...',
      'Renaming folder...' => '폴더 이름 변경중...',
      'Please wait while the selected files are being zipped...' => '선택한 파일의 압축이 해제되는 동안 기다리십시오...',
      'Please wait while the selected folder is being zipped...' => '선택한 폴더의 압축이 해제되는 동안 기다리십시오...',
      'Selected Files.zip' => '선택한 파일.zip',
      'Downloading zip file...' => 'zip 파일을 다운로드하는 중...',
      'Are you sure you want to delete the selected file(s)?' => '선택한 파일을 삭제하시겠습니까?',
      'The selected folder and all its contents will be deleted.' => '선택한 폴더와 폴더의 모든 내용이 삭제됩니다.',
      'Permanent deletion' => '영구 삭제',
      'New Folder' => '새로운 폴더',
      'Creating new folder...' => '새로운 폴더 생성 중...',
      'Please type a folder name for the archive contents:' => '아카이브 컨텐츠의 폴더 이름을 입력하십시오:',
      'Extracted Files' => '추출된 파일',
      'Deleted from' => '삭제됨',
      'Trash' => '휴지통',
      'Restore' => '복구',
      'Recent' => '최근',
      'Shared by me' => '내가 공유한 파일',
      'There are no shared files or folders' => '공유 파일 또는 폴더가 없습니다.',
      'Files' => '파일',
      'There are no recently accessed files' => '최근에 액세스한 파일이 없습니다.',
      'Activity' => '폴더 활성화',
      'Please type a name for the zip file:' => 'zip 파일의 이름을 입력하십시오:',
      'New Archive.zip' => '새 압축.zip',
      'Activity log' => '활동 로그',
      'Loading the file\'s activity log...' => '파일의 작업 로그를 로드하는 중..',
      'External Window' => '외부 창',
      'Folders' => '폴더',
      'Zip and download' => 'Zip & 다운로드',
      'This type of archives is not supported by the current server configuration.' => '이 유형의 아카이브는 현재 서버 구성에서 지원되지 않습니다.',
      'One item' => '하나의 아이템',
      'One item selected' => '1 항목이 선택 됨',
      'More' => '더 보기',
      'Confirm' => '확인',
      'Details' => '상세 정보',
      'My Files' => '내 파일',
      'Upload to "%1"' => '"%1" 로 업로드 중',
      'Folder upload' => '폴더 업로드',
      'File upload' => '파일 업로드',
      'Create new' => '새로 만들기',
      'Add Files' => '파일 추가',
      'Add Folder' => '폴더 추가',
      'Remove from queue' => '대기열에서 제거',
      'Cancel' => '취소',
      'Cancel all' => '모두 취소',
      'Skip file' => '파일 건너뛰기',
      'Resume file' => '파일 다시 시작',
      'Pause all' => '모두 중지',
      'File name' => '파일 이름',
      'Uploaded' => '전송 용량',
      'Progress' => '진행 상태',
      'Speed' => '속도',
      'Time remaining' => '남은 시간',
      '%1 files left' => '%1 파일 남음',
      '%1 of %2' => '%1 중 %2',
      '[Skipped]' => '[건너뛰기]',
      'Paused' => '중지',
      'Uploading (Retry #%1)...' => '업로드 중... (시도 #%1)',
      'Paused (%1%)' => '중지 (%1%)',
      'Waiting (100%)' => '대기 (100%)',
      'Server error' => '서버 오류',
      'A problem has been encountered!' => '문제가 발생했습니다!',
      'Try again' => '다시 시도',
      '%1 hours' => '%1 시간',
      '%1 minutes' => '%1 분',
      '%1 seconds' => '%1 초',
      'You are not allowed to upload the file "%1"' => '"%1" 파일을 업로드할 수 없음',
      'There are no comments for this item' => '이 항목에 대한 코멘트가 없습니다.',
      'Write a comment...' => '코멘트 작성...',
      'Contents' => '콘텐츠',
      'Use the displayed header bar to sort by the desired field.' => '표시 된 헤더 막대를 사용하여 원하는 필드를 기준으로 정렬합니다.',
      'Drop files here' => '여기로 파일을 드롭하세요',
      'or use the "NEW" button' => '또는 "새로운 추가" 버튼을 사용하십시오.',
      'Queued' => '대기 중',
      'Mute sound notifications' => '음소거 알림',
      'Notifications' => '알림',
      'Add to cart' => '카트에 추가',
      'Download cart' => '카트 다운로드',
      'Label' => '라벨',
      'No label' => '라벨 없음',
      'Custom label' => '사용자 지정 라벨',
      'New label' => '새로운 라벨',
      'Page' => '페이지',
      'of {0}' => '{0}의',
      'First Page' => '처음 페이지',
      'Last Page' => '마지막 페이지',
      'Next Page' => '다음 페이지',
      'Previous Page' => '이전 페이지',
      'Uploading pasted image...' => '붙여넣은 이미지를 업로드하는 중...',
      'Pasted image' => '붙여넣은 이미지',
      'Pasted image successfully uploaded' => '붙여넣은 이미지가 업로드 됨',
      'Are you sure you want to remove the comment?' => '코멘트를 지우시겠습니까?',
      '%1 of %2 results' => '%2 결과 중 %1개',
      '%1 results' => '%1 결과',
      'Show more...' => '더 보기',
      'Star' => '별',
      'Starred' => '즐겨찾기',
      'Remove star' => '즐겨찾기에서 제거',
      'There are no starred files or folders' => '즐겨찾기 한 파일이나 폴더가 없습니다',
      'There are no shared links' => '공유 링크가 없습니다',
      'Folder' => '폴더',
      'File' => '파일',
      'More options' => '더 많은 옵션',
      'Location' => '위치',
      'Please wait as loading the file might take a while...' => '파일을 로드하는 데 시간이 좀 걸릴 수 있으므로 기다려 주십시오...',
      'New' => '새로운 추가',
      'Shared links' => '공유 링크',
      'Locate' => '위치',
      'Next' => '다음',
      'Previous' => '이전',
      'Close' => '닫기',
      'Zoom' => '확대',
      'First page' => '처음 페이지',
      'Page %1' => '페이지 %1',
      'You are required to change your password.' => '비밀번호를 변경해야합니다.',
      'No file was found matching your search criteria.' => '검색 조건과 일치하는 파일을 찾을 수 없습니다.',
      'To upload files, drag them from your computer' => '파일을 업로드하려면 컴퓨터에서 끌어다 놓습니다.',
      'Account settings' => '계정 설정',
      'Download all' => '모두 다운로드',
      'Use "Page Down" and "Page Up" to change the page' => '페이지를 변경하려면 "Page Down" 및 "Page Up" 키를 사용합니다.',
      'Empty trash' => '빈 휴지통',
      'Emptying trash...' => '휴지통을 비우는 중...',
      'Empty trash?' => '휴지통을 비우시겠습니까?',
      'All files and folders in your trash are about to be permanently deleted.' => '당신의 휴지통에 모든 파일 및 폴더가 영구적으로 삭제됩니다.',
      'An error occurred while trying to process the request.' => '요청을 처리하는 동안 오류가 발생했습니다.',
      'Resume' => '재개',
      'Delete folder?' => '폴더를 삭제할까요?',
      'Please enter a new name for the item:' => '항목에 대한 새 이름을 입력하세요:',
      'Are you sure you want to move the folder?' => '폴더를 이동하시겠습니까?',
      'Move folder?' => '폴더를 이동할까요?',
      'Web link' => '웹 링크',
      'Please type the %1label\'s text%2' => '%1라벨의 텍스트 %2을 입력해 주십시오.',
      'Tags' => '태그',
      'Failed to load file list.' => '파일 목록을 로드하지 못했습니다.',
      'You need a modern browser in order to use this feature.' => '이 기능을 사용하려면 최신 브라우저가 필요합니다.',
      'Please select a PNG or JPG image file.' => 'PNG 또는 JPG 이미지 파일을 선택하세요.',
      'File request' => '파일 요청',
      'What are you requesting?' => '무엇을 요구하십니까?',
      'Photos, Documents, Contracts...' => '사진, 문서, 파일 등',
      'Shared with' => '함께 공유',
      'Search options' => '검색 옵션',
      'Create new folder' => '새로운 폴더 만들기',
      'This field is required' => '이 필드는 필수입니다.',
      'Photos' => '사진',
      'Uploading...' => '업로드 중...',
      'Help' => '도움',
      'Date deleted' => '날짜 삭제',
      'Search in' => '검색',
      'Display mode' => '디스플레이 모드',
      'Detailed list' => '자세한 목록',
      'Thumbnails' => '썸네일',
      'Last taken' => '마지막으로 이동 된 항목',
      'By date' => '날짜',
      'By tag' => '태그',
      'Music' => '노래',
      'Last added' => '마지막으로 추가 된 시간',
      'By artist' => '아티스트',
      'By album' => '앨범',
      'Random' => '랜덤',
      'Failed to load audio file.' => '오디오 파일을 로드하지 못했습니다.',
      'There are no photos in here' => '여기에 사진이 없습니다.',
      'There are no audio files in here' => '여기에 오디오 파일이 없습니다.',
      'There is one other item' => '여기에 하나의 항목도 없습니다.',
      'There are %1 other items' => '여기에 %1 개의 다른 항목이 있습니다.',
      'Show all items' => '모든 항목 보기',
      'Show the item' => '항목 보기',
      'Scan files for changes' => '파일을 검사하여 변경 사항을 확인합니다.',
      'This folder is empty' => '이 폴더는 비어있습니다.',
      'Tag files' => '태그 파일',
      'Please select at least a file or a folder!' => '파일이나 폴더를 선택하세요!',
      'Please add at least one tag!' => '태그를 하나 이상 추가하세요!',
      'Add tags...' => '태그 추가',
      'Tag selected' => '선택 된 태그',
      'No comments available for this item' => '이 항목은 코멘트가 없습니다',
      'Hide details' => '상세 정보 숨기기',
      'Available options' => '사용 가능한 옵션',
      'Collections' => '컬렉션',
      'Add to' => '새로 추가',
      'Collection..' => '컬렉션',
      'Create a new collection' => '새로운 컬렉션 만들기',
      'Adding files to collection...' => '컬렉션에 파일 추가 중...',
      'Are you sure you want to remove the collection?' => '정말로 컬렉션을 지우시겠습니까?',
      'Removing collections...' => '컬렉션을 제거하는 중입니다...',
      'Remove from collection' => '컬렉션에서 제거',
      'Removing items from collection...' => '컬렉션에서 항목을 제거하는 중...',
      'Creating a new collection...' => '새 컬렉션을 만드는 중...',
      'There are no collections' => '여기에 컬렉션이 없습니다',
      'Move' => '이동',
      'Move here' => '여기로 이동',
      'Copy here' => '여기로 복사',
      'Select folder' => '폴더 선택',
      'Create a new folder' => '새로운 폴더 생성',
      'There are no folders in here' => '여기에 폴더가 없습니다',
      'Failed to load data!' => '데이터를 불러오지 못했습니다!',
      'Clear list' => '리스트 지우기',
      'Add files to the download cart by dragging them onto the cart icon (%1)' => '파일을 카트 아이콘(%1)으로 끌어 다운로드 카트에 추가합니다.',
    ),
    'General' => 
    array (
      'One minute ago' => '1분 전',
      'One minute' => '1분',
      'Copying...' => '복사 중...',
      'Submit' => '전송',
      'Save' => '저장',
      'Cancel' => '취소',
      'Error' => '오류',
      'Invalid path.' => '잘못된 경로',
      'File not found!' => '파일을 찾을 수 없습니다!',
      'You are not allowed to preview the selected file.' => '선택한 파일을 미리 볼 수 없습니다.',
      '%1 users' => '%1 사용자',
      'You are not allowed to download the requested file!' => '요청된 파일을 다운로드할 수 없습니다!',
      'The file you are trying to download is no longer available!' => '다운로드하려는 파일을 더 이상 사용할 수 없습니다!',
      'You are not allowed to download or preview files.' => '파일을 다운로드하거나 미리 볼 수 없습니다.',
      'Invalid folder.' => '잘못된 폴더입니다.',
      'You are not allowed to copy that shared file.' => '해당 공유 파일을 복사할 수 없습니다.',
      'You are not allowed to copy files to the specified target.' => '지정된 대상에 파일을 복사할 수 없습니다.',
      'No file was copied!' => '복사된 파일이 없습니다!',
      'One file copied.' => '파일 하나가 복사되었습니다.',
      '%1 files copied.' => '%1 파일이 복사되었습니다.',
      'No more file space available.' => '사용 가능한 파일 공간이 더 이상 없습니다.',
      'You are not allowed to delete files from this shared folder.' => '이 공유 폴더에서는 파일을 삭제할 수 없습니다.',
      'No files were deleted!' => '삭제된 파일이 없습니다!',
      'One file deleted.' => '파일 하나가 삭제되었습니다.',
      '%1 files successfully deleted.' => '%1 파일이 삭제되었습니다.',
      'You are not allowed to move that shared file.' => '공유 파일을 이동할 수 없습니다.',
      'You are not allowed to move files to the specified target.' => '지정된 대상으로 파일을 이동할 수 없습니다.',
      'You are not allowed to move these shared files to your own folder.' => '이러한 공유 파일은 자신의 폴더로 이동할 수 없습니다.',
      'No file was moved!' => '파일을 이동하지 않았습니다!',
      'One file moved.' => '파일 하나가 이동되었습니다.',
      '%1 files moved.' => '%1 파일이 이동되었습니다.',
      'Invalid target path, file already exists.' => '잘못된 대상 경로입니다. 파일이 이미 있습니다.',
      'The selected file is currently locked by another user.' => '선택한 파일이 현재 다른 사용자에 의해 잠겨 있습니다.',
      'Invalid path, not a file.' => '파일이 아닌 잘못된 경로입니다.',
      'Invalid path, not a folder.' => '폴더가 아닌 잘못된 경로입니다.',
      'Invalid source path, not a folder.' => '폴더가 아닌 잘못된 원본 경로입니다.',
      'Invalid target path, not a folder.' => '폴더가 아닌 잘못된 대상 경로입니다.',
      'Invalid source path, not a file.' => '파일이 아닌 잘못된 원본 경로입니다.',
      'You are not allowed to rename files in this shared folder.' => '이 공유 폴더의 파일 이름은 변경할 수 없습니다.',
      'File successfully renamed.' => '파일 이름을 변경했습니다.',
      'There is already a file or a folder with the same name!' => '같은 이름의 파일이나 폴더가 이미 있습니다!',
      'Failed to rename file!' => '파일 이름을 바꾸지 못했습니다!',
      'You are not allowed to extract archives in this shared folder.' => '이 공유 폴더에서는 아카이브를 추출할 수 없습니다.',
      'You are not allowed to zip files in this shared folder.' => '이 공유 폴더에서는 파일의 압축을 풀 수 없습니다.',
      'Invalid folder name!' => '폴더 이름이 잘못되었습니다!',
      'Invalid file name' => '파일 이름이 잘못되었습니다.',
      'A folder with that name already exists!' => '해당 이름의 폴더가 이미 있습니다!',
      'Unzipped Files' => '압축이 풀린 파일입니다.',
      'The archive was successfully extracted.' => '아카이브를 성공적으로 추출했습니다.',
      'Invalid zip name!' => 'zip 이름이 잘못되었습니다!',
      'You are not allowed to upload to this shared folder.' => '이 공유 폴더에 업로드할 수 없습니다.',
      'No more file space available!' => '사용 가능한 파일 공간이 더 이상 없습니다!',
      'File uploaded.' => '파일이 업로드되었습니다.',
      '%1 minutes' => '%1 분',
      '%1 minutes ago' => '%1 분 전',
      'One hour' => '1시간',
      'One hour ago' => '1시간 전',
      '%1 hours' => '%1 시간',
      '%1 hours ago' => '%1 시간 전',
      'One day' => '1일',
      'One day ago' => '1일 전',
      'Yesterday' => '하루 전',
      '%1 days' => '%1 일',
      '%1 days ago' => '%1 일 전',
      'One week' => '1주',
      'One week ago' => '1주 전',
      '%1 weeks' => '%1 주',
      '%1 weeks ago' => '%1 주 전',
      'You are not allowed to delete this shared item.' => '이 공유 항목을 삭제할 수 없습니다.',
    ),
    'DateTime' => 
    array (
      'This month' => '당 월',
      'January' => '1월',
      'February' => '2월',
      'March' => '3월',
      'April' => '4월',
      'May' => '5월',
      'June' => '6월',
      'July' => '7월',
      'August' => '8월',
      'September' => '9월',
      'October' => '10월',
      'November' => '11월',
      'December' => '12월',
      'Sunday' => '일요일',
      'Monday' => '월요일',
      'Tuesday' => '화요일',
      'Wednesday' => '수요일',
      'Thursday' => '목요일',
      'Friday' => '금요일',
      'Saturday' => '토요일',
      'Today' => '오늘',
      'This date is before the minimum date' => '이 날짜는 최소 날짜 이전입니다.',
      'This date is after the maximum date' => '이 날짜는 최대 날짜 이후입니다.',
      'Next Month (Control+Right)' => '다음 달',
      'Previous Month (Control+Left)' => '이전 달',
      'Choose a month (Control+Up/Down to move years)' => '달 선택',
      'Cancel' => '취소',
      'Jan' => '1월',
      'Feb' => '2월',
      'Mar' => '3월',
      'Apr' => '4월',
      'Jun' => '6월',
      'Jul' => '7월',
      'Aug' => '8월',
      'Sep' => '9월',
      'Oct' => '10월',
      'Nov' => '11월',
      'Dec' => '12월',
    ),
    'File Upload' => 
    array (
      'File uploaded' => '파일이 업로드 되었습니다',
      'Failed to upload file' => '파일을 업로드하지 못했습니다',
      'Failed to create folder' => '폴더를 만들지 못 했습니다',
      'Failed to upload file "%1": %2' => '파일을 업로드하지 못했습니다 "%1" : %2',
      'The monthly traffic limit has been reached!' => '월 트래픽 한도에 도달했습니다!',
      'No more file space available!' => '사용 가능한 파일 공간이 더 이상 없습니다!',
      'A file named "%1" already exists!' => '"%1" 이라는 파일이 이미 있습니다!',
      'The file needs to be uploaded from the beginning.' => '파일을 처음부터 업로드해야 합니다.',
      'Failed to transfer data. Make sure you are not trying to upload an empty folder.' => '데이터를 전송하지 못했습니다. 빈 폴더를 업로드하지 않도록 합니다.',
      'You are not allowed to upload to this shared folder.' => '이 공유 폴더에 업로드할 수 없습니다.',
      'Failed to upload file part' => '부분 파일을 업로드하지 못 했습니다',
      'Failed to upload file. Please try again.' => '업로드에 실패하였습니다. 다시 시도해주세요.',
    ),
    'Share Files' => 
    array (
      'Upload' => '업로드',
      'Add comments' => '코멘트 추가',
      'Read comments' => '코멘트 읽기',
      'Share anonymously' => '익명으로 공유',
      'Share with' => '공유',
      'Select Users' => '사용자 선택',
      'Cancel' => '취소',
    ),
    'Folder Notifications' => 
    array (
      'Notification settings successfully saved' => '알림 설정이 저장되었습니다',
      'Notifications for "read" actions cannot be set on shared folders.' => '공유 폴더에 "읽기" 작업을 설정할 수 없습니다.',
      'No changes were made.' => '변경 사항이 없습니다.',
    ),
    'Searching' => 
    array (
      'File name' => '파일명',
      'File contents' => '파일 내용',
      'Look in' => '보세요',
      'Metadata Field' => '메타데이터 필드',
      'Metadata' => '메타데이터',
      'Select...' => '선택...',
      'Path' => '경로',
      'Searching...' => '검색 중...',
      'Search' => '검색',
      '- None Selected -' => '- 선택되지 않음 -',
      'Metadata Type' => '메타데이터 유형',
      'Field Value' => '필드 값',
    ),
    'Custom Actions: CloudConvert' => 
    array (
      'API Key' => 'API 키',
      'Convert "%1" to:' => '"%1"을 다음으로 변환합니다.',
      'No conversion option found for the "%1" file type.' => '"%1" 파일 유형에 대한 변환 옵션을 찾을 수 없습니다.',
    ),
    'File Comments' => 
    array (
      'Author' => '작성자',
      'Comment' => '코멘트',
      'Add comment' => '코멘트 추가',
      'Type in your comment' => '코멘트를 입력하세요',
      'Remove comment' => '코멘트 지우기',
      'You are not allowed to read comments.' => '코멘트를 읽을 수 없습니다.',
      'You are not allowed to add comments.' => '코멘트를 추가 할 수 없습니다.',
      'You are not allowed to remove comments.' => '코멘트를 지울 수 없습니다.',
      'You are not allowed to add comments to files in this shared folder.' => '이 공유 폴더의 파일에 코멘트를 추가할 수 없습니다.',
      'You are not allowed to remove comments from files in this shared folder.' => '이 공유 폴더의 파일에서 코멘트를 제거할 수 없습니다.',
      'You are allowed to delete only your own comments from a shared file.' => '공유 파일에서 사용자 자신의 코멘트만 지울 수 있습니다.',
      'You are not allowed to read comments in this shared folder.' => '이 공유 폴더에서는 코멘트를 읽을 수 없습니다.',
      'No comments available for this file.' => '이 파일에 코멘트가 없습니다.',
      'Comment successfully added.' => '코멘트가 작성되었습니다.',
      'Failed to add comment to file.' => '코멘트를 추가 하지 못했습니다.',
      'Comment successfully removed.' => '코멘트를 지웠습니다.',
      'Failed to remove comment from file.' => '코멘트를 지우지 못했습니다.',
    ),
    'Custom Actions: Text Editor' => 
    array (
      'Text Editor' => '텍스트 에디터',
      'Text File' => '텍스트 파일',
      'Untitled.txt' => '제목없음.txt',
      'Save' => '저장',
      'Saving...' => '저장중...',
      'File successfully saved' => '파일이 저장되었습니다.',
      'File successfully created' => '파일이 생성되었습니다.',
      'A file with that name already exists' => '그 이름의 파일이 이미 존재합니다.',
      'Please type a file name' => '파일 이름을 입력하세요',
      'Other..' => '기타..',
      'New Text File.txt' => '새로운 텍스트 파일.txt',
      'Would you like to reload the file using the selected charset? Any unsaved changes will be lost.' => '선택한 문자 집합을 사용하여 파일을 다시 로드하시겠습니까? 저장되지 않은 변경 내용은 모두 손실됩니다.',
      'Save and close' => '저장 하고 닫기',
      'Word wrap' => '자동 줄 바꿈',
      'The file type is not allowed.' => '그 파일 형식은 허용되지 않습니다.',
      'Close' => '닫기',
    ),
    'Custom Actions: Zoho' => 
    array (
      'API key' => 'API 키',
      'Zoho Editor' => '조호 에디터',
      'Document with Zoho' => '조호 문서',
      'Untitled.docx' => '제목없음.docx',
      'Blank file created successfully' => '빈 파일이 생성되었습니다.',
    ),
    'Custom Actions: Image Editor' => 
    array (
      'Apply' => '적용',
      'Close' => '닫기',
      'Save and close' => '저장 하고 닫기',
      'Save' => '저장',
      'Failed to load image!' => '이미지를 불러올 수 없습니다!',
      'Loading image..' => '이미지 불러오는 중..',
      'Cancel' => '취소',
      'Crop' => '자르기',
      'Scale down' => '축소',
      'Rotate' => '회전',
      'Reset' => '초기화',
      'Flip horizontal' => '가로로 뒤집기',
      'Flip vertical' => '세로로 뒤집기',
      'Fit to screen' => '화면 맞춤',
      'Full size' => '전체 화면',
      'Reload image' => '이미지 다시 불러오기',
      'Uploading image..' => '이미지 업로드 중...',
    ),
    'Custom Actions: File Encryption' => 
    array (
      'Path to AESCrypt' => 'AESCrypt 경로',
      'Download and install AESCrypt from <a href="%1" target="_blank">here</a>.' => '< a href="%1" target="_blank">여기</a>에서 AESCrypt를 다운로드하여 설치합니다.',
      'AES File Encryption' => 'AES 파일 암호화',
      'Password' => '비밀번호',
      'Decrypt "%1"' => '해독 "%1"',
      'Encrypt "%1"' => '암호화 "%1"',
      'Processing file...' => '파일 처리 중...',
      'The user doesn\'t have permission to use this function!' => '사용자에게 이 기능을 사용할 수 있는 권한이 없습니다!',
      'The selected file was successfully decrypted.' => '선택한 파일의 암호를 해독했습니다.',
      'Failed to decrypt the selected file!' => '선택한 파일의 암호를 해독하지 못했습니다!',
      'A file named "%1" already exists!' => '"%1" 이라는 파일이 이미 있습니다!',
      'The selected file was successfully encrypted.' => '선택한 파일이 성공적으로 암호화되었습니다.',
      'Failed to encrypt the selected file!' => '선택한 파일을 암호화하지 못했습니다!',
      'The selected file was not found!' => '선택한 파일을 찾을 수 없습니다!',
      'Confirm password' => '비밀번호 확인',
      'Delete the source file' => '원본 파일 제거',
      'Please type the password' => '비밀번호를 입력해 주세요.',
      'Please confirm the password' => '비밀번호를 확인해 주세요.',
    ),
    'Admin: Groups' => 
    array (
      'You are not allowed to delete groups.' => '그룹을 삭제할 수 없습니다.',
      'You are not allowed to manage user groups.' => '사용자 그룹을 관리 할 수 ​​없습니다.',
      'You are not allowed to manage this group.' => '이 그룹을 관리 할 수 ​​없습니다.',
      '(%1 users)' => '(%1 사용자)',
      'Group successfully created!' => '그룹이 성공적으로 생성되었습니다!',
      'Add a new user groups.' => '새로운 사용자 그룹 추가',
      'Please type a name for the group!' => '그룹의 이름을 입력하세요!',
      'Please don\'t use special characters for the group\'s name!' => '그룹 이름에 특수 문자를 사용하지 마십시오!',
      'Group name already used. Please choose another one.' => '이미 사용 된 그룹 이름입니다. 다른 것을 선택하십시오.',
      'Failed to create group!' => '그룹을 만들지 못했습니다!',
      'Groups' => '그룹',
      'Create group' => '그룹 생성',
      'Group name' => '그룹 이름',
      'Description' => '설명',
      'Failed to edit group!' => '그룹을 편집하지 못했습니다!',
      'Edit group' => '그룹 편집',
      'Delete group' => '그룹 삭제',
      'Failed to delete group!' => '그룹을 삭제하지 못했습니다!',
      'Please confirm group deletion.' => '그룹 삭제를 확인하십시오.',
      'Delete' => '삭제',
      'Edit group.' => '그룹 편집.',
      'Delete group.' => '그룹 삭제.',
      'Group successfully deleted!' => '그룹이 삭제되었습니다!',
      'Name' => '이름',
      'Created by' => '만든 이',
      'Users' => '사용자',
      'Add Group' => '그룹 추가',
      'Group successfully updated!' => '그룹이 업데이트 되었습니다!',
    ),
    'Admin: Logs' => 
    array (
      'Date Format: Grid - Date' => 'Y-M-d H:i:s',
      'Activity logs' => '활성화 된 로그',
      'Toggle search options' => '검색 옵션 토글',
      'User' => '유저',
      'Users' => '모든 유저',
      'Actions' => '활동 내용',
      'Date start' => '날짜 시작',
      'Date end' => '날짜 끝',
      'Search' => '검색',
      'Loading data...' => '데이터 불러오는 중...',
      'Date' => '날짜',
      'Details' => '상세',
      'Keyword' => '키워드',
      'Please confirm the archiving and deletion of the activity logs.' => '활동 로그의 보관 및 삭제를 확인해 주세요.',
      'Activity log has been successfuly archived!' => '활동 로그가 성공적으로 보관되었습니다!',
      'Failed to retrieve log data!' => '로그 데이터를 검색하지 못했습니다!',
      'Failed to create archive file!' => '아카이브 파일을 생성하지 못했습니다!',
      'Failed to clear logs!' => '로그를 지우지 못했습니다!',
      'Failed to archive logs!' => '로그를 보관하지 못했습니다!',
      'You are not allowed to access the activity logs.' => '작업 로그에 액세스할 수 없습니다.',
      'Export results to CSV' => 'CSV 내보내기 결과',
      'Action' => '활동',
      'Search Activity Logs' => '활동 로그 검색',
      'Export' => '내보내기',
    ),
    'Admin: Metadata' => 
    array (
      'You cannot delete this file type.' => '이 파일 형식은 삭제할 수 없습니다.',
      'Metadata' => '메타데이터',
      'Manage the different types of information that can be associated with classes of files.' => '파일 클래스와 연결할 수 있는 다양한 유형의 정보를 관리합니다.',
      'You are not allowed to manage the metadata settings.' => '메타데이터 설정을 관리할 수 없습니다.',
      'Fieldsets' => '필드셋',
    ),
    'Admin: Tools: Import Users' => 
    array (
      'Comma' => '콤마',
      'Semicolon' => '세미콜론',
      'Tab' => '탭',
      'Import Users' => '유저 불러오기',
      'Step 1: Upload CSV File' => '1단계: CSV파일 업로드',
      'Step 2: Map Fields' => '2단계: 맵 필드',
      'Step 3: Import Users' => '3단계: 유저 불러오기',
      'Upload CSV file' => 'CSV 파일 업로드',
      'Only CSV files are supported!' => 'CSV 파일만 지원합니다!',
      'The CSV file should have at least two columns!' => 'CSV 파일에는 적어도 두 개의 열이 있어야 합니다!',
      'Fields are separated by' => '필드는 다음으로 구분됩니다.',
      'Uploading...%1%' => '업로드 중... %1%',
      'Upload starting...' => '업로드 시작...',
      '%1 records were found' => '%1 개의 레코드가 발견되었습니다.',
      'Assign a role to the users' => '사용자에게 역할을 할당합니다.',
      'Add the users to groups' => '사용자를 그룹에 추가합니다.',
      'Start with record number' => '레코드 번호로 시작',
      'Failed to parse file contents!' => '파일 내용을 구문 분석하지 못했습니다!',
      'Only the first 10 records are being displayed here.' => '여기에 처음 10개의 레코드만 표시됩니다.',
      'Username' => '사용자명',
      'Password' => '비밀번호',
      'Name 1' => '이름',
      'Name 2' => '이름',
      'Name 3' => '이름',
      'E-mail' => '이메일',
      'Company' => '회사',
      'Website' => '웹사이트',
      'Note' => '노트',
      'You need to map a column for the username!' => '사용자 이름에 대한 열을 매핑해야 합니다!',
      'You need to map a column for the password!' => '암호에 대한 열을 매핑해야 합니다!',
      'You need to map at least one column for the name!' => '이름에 대해 열을 하나 이상 매핑해야 합니다!',
      'The selected role was not found!' => '선택한 역할을 찾을 수 없습니다!',
      'Record %1: The username is missing! The record was skipped.' => '%1 레코드: 사용자 이름이 없습니다! 레코드를 건너뛰었습니다.',
      'Record %1: The name is missing! The record was skipped.' => '%1 레코드: 이름이 없습니다! 레코드를 건너뛰었습니다.',
      'Record %1: The password is missing! The record was skipped.' => '%1 레코드: 암호가 없습니다! 레코드를 건너뛰었습니다.',
      'Record %1: The username "%2" is already in use! The record was skipped.' => '%1 레코드: "%2" 사용자 이름이 이미 사용 중입니다! 레코드를 건너뛰었습니다.',
      'Record %1: User "%2" has been added. Password: %3' => '%1 레코드: 사용자 "%2"가 추가되었습니다. 암호: %3',
      'Passwords are in clear text' => '암호가 비어있습니다',
      'Enable this option if the passwords stored in your CSV files are not encrypted.' => 'CSV 파일에 저장된 암호가 암호화되지 않은 경우 이 옵션을 사용하도록 설정합니다.',
      'Record number' => '레코드 번호',
      'Username/E-mail' => '사용자명/이메일',
      'Send a notification now' => '알림 보내기',
      'An e-mail message with the login information will be sent to the user\'s address.' => '로그인 정보가 포함된 이메일 메시지가 사용자의 주소로 전송됩니다.',
      'The CSV file needs to contain at least two columns, for username and name.' => 'CSV 파일에는 사용자 이름과 같은 열이 두 개 이상 포함되어야 합니다.',
      'You will be asked to map the fields, so the names and the order of the columns are not important.' => '필드의 맵을 지정하라는 메시지가 표시되므로 열의 이름과 순서는 중요하지 않습니다.',
    ),
    'Metadata: Custom' => 
    array (
      'Image proprieties' => '이미지 소유권',
      'Audio proprieties' => '오디오 소유권',
      'Height' => '높이',
      'Width' => '넓이',
      'Codec' => '코덱',
      'Duration' => '지속',
      'Various information' => '다양한 정보',
      'Author' => '제작자',
      'Description' => '설명',
      'Caption' => '설명',
      'Copyright' => '저작권',
      'GPS latitude' => 'GPS 위도',
      'GPS longitude' => 'GPS 경도',
      'Movie title' => '영화 제목',
      'Subject' => '제목',
      'Album' => '앨범',
      'Artist' => '아티스트',
      'Title' => '제목',
      'Location' => '장소',
      'Tags' => '태그',
      'Date Created' => '만든 날짜',
      'Rating' => '점수',
    ),
    'Labels' => 
    array (
      'APPROVED' => '인증 됨',
      'PENDING' => '보류 중',
      'REJECTED' => '거부 됨',
      'Failed to insert new label' => '새 라벨을 삽입하지 못했습니다',
      'No files were labeled' => '라벨이 지정된 파일이 없습니다',
      'File successfully labeled' => '파일이 성공적으로 분류되었습니다',
      '%1 files successfully labeled' => '%1 개 파일이 성공적으로 라벨링되었습니다',
      'Label successfully removed' => '라벨이 제거되었습니다',
      'Labels successfully removed from %1 files' => '%1 파일에서 라벨이 성공적으로 제거되었습니다',
    ),
    'Custom Actions: MediaInfo' => 
    array (
      'Media Info' => '미디어 정보',
    ),
    'Custom Actions: 3D Viewer' => 
    array (
      '3D Viewer' => '3D 뷰어',
      'Loading..' => '불러오는 중..',
      'Save as PNG' => 'PNG로 저장',
      'Failed to load model' => '모델을 로드하지 못했습니다',
      'Loading file..' => '파일 불러오는 중..',
      'Loading resources..' => '리소스 불러오는 중..',
      'Rendering model..' => '모델 렌더링 중..',
      'This file format cannot be handled.' => '이 파일 형식은 처리할 수 없습니다.',
      'Getting image..' => '이미지 가져오는 중...',
      'Uploading image..' => '이미지 업로드 중..',
    ),
    'Admin: Tools: Export Users' => 
    array (
      'Export' => '내보내기',
    ),
    'OAuth2' => 
    array (
      'OAuth2 Consent' => 'OAuth2 동의',
      'List files and folders in your "%1" account.' => '파일에 파일 및 폴더 나열 "%1"',
      'Would like to receive full access to:' => '모든 권한을 얻겠습니까?',
      'Would like to receive <a href="javascript:showAccess()">access</a> to:' => '받고싶나요?',
      'Use of your data is subject to the privacy policy of <span class="nowrap-bold">%1</span>.' => '데이터 사용은 다음 개인 정보 보호 정책의 적용을 받는다.',
      'Your account is configured for 2-step verification.' => '2단계 검증을 구성할 수 있습니다.',
      'Please provide your <strong>%1</strong> credentials.' => '<strong>%1</strong> 자격 증명을 제공하십시오.',
      '1. Select and copy the following key code:' => '키 코드를 선택하고 복사하십시오.',
      '2. Open your 2-step verification app and create an account with this key code.' => '2단계 검증 앱을 열고 이 키 코드를 사용하여 계정을 만드십시오.',
      '3. Lastly, copy the generated verification code (not the one above) from the app to the field bellow.' => '마지막으로 생성된 검증 코드(위 내용이 아님)를 앱에서 아래 필드로 복사하십시오.',
      'Verification code' => '인증 코드',
      'Username' => '사용자명',
      'Password' => '비밀번호',
      'Proceed' => '진행',
      'View your e-mail address, although your account currently doesn\'t have one set.' => '이메일을 확인하세요.',
    ),
    'Custom Actions: Google Editor' => 
    array (
      'Read the <a href="%1" target="_blank">configuration guide</a>.' => '<a href="%1" target="_blank">구성 가이드</a>를 읽습니다.',
      'OAuth Client Secret' => 'OAuth 비밀 클라이언트',
      'OAuth Client ID' => 'OAuth 클라이언트 ID',
      'Signing into Google...<br>Please check the opened popup for proceeding to the editor.' => '구글로 보내는 중...<br>열린 팝업을 확인하여 편집기를 진행하시기 바랍니다.',
      'Sending document data to Google...<br>Please wait.' => '문서 데이터를 구글로 보내는 중 입니다.<br>잠시만 기다려주세요.',
      'Waiting for the editor to close...<br>If you close this window, your changes will not be saved to the document.' => '편집기가 닫히기를 기다리고 있습니다.<br>이 창을 닫으면 변경 내용이 문서에 저장되지 않습니다.',
      'Importing document from Google...' => '구글에서 문서를 가져오는 중입니다...',
      'Blank file created successfully' => '빈 파일이 생성되었습니다.',
      'Document with Google' => '구글로 문서화',
    ),
    'Custom Actions: Audio Player' => 
    array (
      'Audio Player' => '오디오 플레이어',
      'Select' => '선택',
      'Loading audio player...' => '오디오 플레이어 로딩 중...',
      'Close player' => '플레이어 닫기',
      'Previous' => '이전',
      'Play/Pause' => '재생/멈춤',
      'Next' => '다음',
      'Shuffle' => '섞기',
    ),
    'Custom Actions: Archive Explorer' => 
    array (
      'Archive Explorer' => '아카이브 탐색기',
    ),
    'Custom Actions: Video Player' => 
    array (
      'Video Player' => '비디오 플레이어',
    ),
    'Custom Actions: Image Viewer' => 
    array (
      'Image Viewer' => '이미지 뷰어',
    ),
    'Custom Actions: ONLYOFFICE' => 
    array (
      'Download and install %1' => '다운로드 및 설치 %1',
      'DocumentServer URL' => '온리오피스 서버 URL',
      'Document with ONLYOFFICE' => '온리오피스 문서',
      'New Document.docx' => '새 문서.docx',
      'New Spreadsheet.xlsx' => '새 스프레드시트.xlsx',
      'New Presentation.pptx' => '새 프레젠테이션.pptx',
      'Presentation' => '프레젠테이션',
      'Spreadsheet' => '스프레드시트',
      'Word Document' => '워드 문서',
      'The file extension needs to be one of the following: %1' => '파일 확장명은 다음 중 하나여야 합니다: %1',
      'A file with the specified name already exists. Please try again.' => '지정한 이름의 파일이 이미 있습니다. 다시 시도해보세요.',
      'Blank file created successfully' => '빈 파일을 생성했습니다.',
    ),
    'Custom Actions: Zamzar' => 
    array (
      'API key' => 'API 키',
      'Zamzar' => '잠자르',
    ),
    'Custom Actions: Autodesk' => 
    array (
      'API client ID' => 'API 클라이언트 ID',
      'API client secret' => 'API 클라이언트 비밀',
    ),
    'Custom Actions: Office' => 
    array (
      'Office' => '오피스',
    ),
    'Custom Actions: Google Earth' => 
    array (
      'Google Maps' => '구글 맵스',
    ),
    'Custom Actions' => 
    array (
      'New tab' => '새로운 탭',
    ),
    'Custom Actions: E-book Reader' => 
    array (
      'E-book Reader' => 'E-Book 리더',
      'Menu' => '메뉴',
      'Fullscreen' => '전체 화면',
    ),
    'Custom Actions: Photo Proof Sheet' => 
    array (
      'Create photo proof sheet' => '교정지 만들기',
      'Photo proof sheet successfully created in your home folder.' => '당신의 홈 폴더에 교정지가 생성되었습니다.',
    ),
    'Custom Actions: Bing Maps' => 
    array (
      'Bing Maps API Key' => 'Bing Maps API 키',
    ),
    'Admin: Guest Users' => 
    array (
      'Enable guest user accounts' => '손님 계정 활성화',
    ),
    'Custom Actions: HTML Editor' => 
    array (
      'HTML Editor' => 'HTML 편집기',
      'Save' => '저장',
      'Save and close' => '저장 하고 닫기',
      'Close' => '닫기',
      'Unsaved changes' => '저장되지 않은 변경 사항입니다.',
      'Discard the changes made?' => '변경 사항을 무시합니까?',
    ),
  ),
);