<?php return array (
  'trans' => 
  array (
    'Login Page' => 
    array (
      'Username' => 'Uporabniško ime',
      'Password' => 'Geslo',
      'Language' => 'Jezik',
      'Sign in' => 'Prijava',
      'Please login.' => 'Prijavite se.',
      'Please type a username.' => 'Vnesite uporabniško ime.',
      'Invalid password.' => 'Neveljavno geslo.',
      'Invalid username.' => 'Neveljavno uporabniško ime.',
      'Your account has been deactivated!' => 'Vaš račun je deaktiviran!',
      'Create account' => 'Ustvari račun',
      'Forgot password?' => 'Ste pozabili geslo?',
      'Signing in...' => 'Prijavljanje ...',
      'Your account access is limited to a particular IP address!' => 'Dostop do vašega računa je omejen na določen naslov IP!',
      '2-step verification: add account' => 'Preverjanje v dveh korakih: dodajte račun',
      'Scan this barcode with the <a href="%1" target="_blank">Google Authenticator</a> app on your mobile device to add your account.' => 'Skenirajte to črtno kodo z aplikacijo <a href="%1" target="_blank">Google Authenticator</a> na mobilni napravi, da dodate svoj račun.',
      'Done' => 'Končano',
      'Your account is configured for 2-step verification. You need to type in a verification code!' => 'Vaš račun je konfiguriran za preverjanje v dveh korakih. Vnesti morate kodo za preverjanje!',
      'The provided verification code is not valid!' => 'Navedena koda za preverjanje ni veljavna!',
      'Your account is configured for 2-step verification. Click Ok to start the setup.' => 'Vaš račun je konfiguriran za preverjanje v dveh korakih. Kliknite V redu, da zaženete namestitev.',
      'Type the following key code into your authentication app:' => 'Vnesite naslednjo kodo ključa v aplikacijo za preverjanje pristnosti:',
      'Verification code' => 'Koda za preverjanje',
      'Please type a password.' => 'Vnesite geslo.',
      'Changing language...' => 'Spreminjanje jezika ...',
      'Loading...' => 'Nalaganje...',
      'There is an Android app that you can use to access your files more comfortably. Would you like to try that instead?' => 'Na voljo je aplikacija za Android, ki jo lahko uporabljate za lažji dostop do datotek. Ali želite to poskusiti?',
      'Add a new <a href="%1" target="_blank">Google Authenticator</a> account with the following key:' => 'Dodajte nov račun <a href="%1" target="_blank">Google Authenticator</a> z naslednjim ključem:',
      '2-step: Add account' => 'Korak 2: Dodaj račun',
      'Authentication should be made with the remote system.' => 'Preverjanje pristnosti je treba opraviti z oddaljenim sistemom.',
    ),
    'Password Reset' => 
    array (
      'The login information has been sent to your email address.' => 'Podatki za prijavo so bili poslani na vaš e-poštni naslov.',
      'Password Reset' => 'Ponastavi geslo',
      'E-mail address' => 'Elektronski naslov',
      'Submit' => 'Pošlji',
      'Please type the e-mail address.' => 'Vnesite e-poštni naslov.',
      'The e-mail address was not found in the database.' => 'E-poštni naslov ni bil najden v bazi podatkov.',
      'Please check your inbox for information on how to reset your account\'s password.' => 'Preverite svojo mapo "Prejeto" za informacije o ponastavitvi gesla računa.',
      'Please wait...' => 'Prosim počakaj...',
      'Sign in' => 'Prijava',
    ),
    'Main Interface' => 
    array (
      'Loading...' => 'Nalaganje...',
      'Sign out' => 'Odjava',
      'Control Panel' => 'Nadzorna plošča',
      'Change password' => 'Spremeni geslo',
      'Preview' => 'Predogled',
      'Sort' => 'Razvrsti',
      'Select All' => 'Izberi vse',
      'Refresh' => 'Osveži',
      'Search' => 'Iskanje',
      'File Search' => 'Iskanje datotek',
      'Share' => 'Deli',
      'New sub-folder' => 'Nova podmapa',
      'Rename' => 'Preimenuj',
      'Remove' => 'Odstraniti',
      'Properties' => 'Lastnosti',
      'Download' => 'Prenesi',
      'Open with..' => 'Odpri z..',
      'Share with users' => 'Delite z uporabniki',
      'Get link' => 'Dobi povezavo',
      'Metadata' => 'Metapodatki',
      'Comment' => 'Komentar',
      'Zip archive..' => 'Dodaj v zip',
      'Extract archive..' => 'Ekstrahiraj',
      'Copy' => 'Kopiraj',
      'Loading file list...' => 'Nalaganje seznama datotek ...',
      'Name' => 'Ime',
      'Size' => 'Velikost',
      'Type' => 'Tip',
      'Meta Type' => 'Vrsta datoteke',
      'Modified' => 'Spremenjeno',
      'Created' => 'Ustvarjeno',
      'Sort Ascending' => 'Razvrsti naraščajoče',
      'Sort Descending' => 'Razvrsti padajoče',
      'Columns' => 'Stolpci',
      'Reset Columns' => 'Ponastavi stolpce',
      'New Folder' => 'Nova mapa',
      'Creating new folder...' => 'Ustvarjanje nove mape ...',
      'Trash' => 'Koš',
      'Shared by me' => 'Deljeno z mano',
      'Files' => 'Datoteke',
      'Folders' => 'Mape',
      'One item selected' => 'Izbran je en element',
      'My Files' => 'Moje datoteke',
      'Upload to "%1"' => 'Naloži v "%1"',
      'Folder upload' => 'Nalaganje mape',
      'File upload' => 'Nalaganje datoteke',
      'Create new' => 'Ustvarite novo',
      'Add Files' => 'Dodaj datoteke',
      'Add Folder' => 'Dodaj mapo',
      'Remove from queue' => 'Odstrani iz čakalne vrste',
      'Cancel' => 'Prekliči',
      'Cancel all' => 'Prekliči vse',
      'Resume file' => 'Nadaljuj datoteko',
      'Pause all' => 'Ustavi vse',
      'File name' => 'Ime datoteke',
      'Uploaded' => 'Naloženo',
      'Progress' => 'Napredek',
      'Speed' => 'Hitrost',
      'Time remaining' => 'Preostali čas',
      '%1 files left' => 'Število preostalih datotek: %1',
      '%1 of %2' => '%1 od %2',
      '[Skipped]' => '[Preskočeno]',
      'Paused' => 'Začasno ustavljeno',
      'Uploading (Retry #%1)...' => 'Nalaganje (poskusi znova #%1) ...',
      'Paused (%1%)' => 'Začasno zaustavljeno (%1%)',
      'Waiting (100%)' => 'Čakanje (100%)',
      'Skip file' => 'Preskoči datoteko',
      'Contents' => 'Vsebina',
      'Label' => 'Oznaka',
      'No label' => 'Brez oznake',
      'Custom label' => 'Oznaka po meri',
      'Starred' => 'Z zvezdico',
      'More options' => 'Več možnosti',
      'New' => 'Novo',
      'Shared links' => 'Deljene povezave',
      'Close' => 'Zapri',
      'Account settings' => 'Nastavitve računa',
      'Download all' => 'Prenesi vse',
      'File request' => 'Zahtevaj datoteko',
      'Photos' => 'Fotografije',
      'Search in' => 'Išči v',
      'Display mode' => 'Način prikaza',
      'Detailed list' => 'Podroben seznam',
      'Thumbnails' => 'Sličice',
      'Last taken' => 'Zadnje ustvarjeno',
      'By date' => 'Po datumu',
      'By tag' => 'Po oznaki',
      'Music' => 'Glasba',
      'Tag files' => 'Označi datoteke',
      'Add tags...' => 'Dodaj oznake...',
      'Tag selected' => 'Izberi oznako',
    ),
    'DateTime' => 
    array (
      'This month' => 'Ta mesec',
      'January' => 'Januar',
      'February' => 'Februar',
      'March' => 'Marec',
      'May' => 'Maj',
      'June' => 'Junij',
      'July' => 'Julij',
      'August' => 'Avgust',
      'October' => 'Oktober',
      'Sunday' => 'Nedelja',
      'Monday' => 'Ponedeljek',
      'Tuesday' => 'Torek',
      'Wednesday' => 'Sreda',
      'Thursday' => 'Četrtek',
      'Friday' => 'Petek',
      'Saturday' => 'Sobota',
      'Today' => 'Danes',
      'This date is before the minimum date' => 'Ta datum je pred minimalnim datumom',
      'This date is after the maximum date' => 'Ta datum je za maksimalnim datumom',
      'Next Month (Control+Right)' => 'Naslednji mesec (Control + Desno)',
      'Previous Month (Control+Left)' => 'Prejšnji mesec (Control + Levo)',
      'Choose a month (Control+Up/Down to move years)' => 'Izberite mesec (Control + Gor / Dol za premikanje let)',
      '{0} (Spacebar)' => '{0} (preslednica)',
      'Cancel' => 'Prekliči',
      'Oct' => 'Okt',
    ),
    'Trash' => 
    array (
      'A file or folder already exists at the original location.' => 'Datoteka ali mapa že obstaja na izvirni lokaciji.',
      'One item permanently deleted.' => 'En element je trajno izbrisan.',
      'No items were restored!' => 'Noben element ni bila obnovljen!',
      'One item restored.' => 'En element je obnovljen.',
      '%1 items successfully restored.' => '%1 elementov je bilo uspešno obnovljenih.',
      'Trash emptied' => 'Koš je izpraznjen',
      'Failed to empty trash' => 'Izpraznitev koša ni uspela',
    ),
    'Account Settings' => 
    array (
      'Current password' => 'Trenutno geslo',
      'New password' => 'Novo geslo',
      'Confirm new password' => 'Potrdite novo geslo',
      'Save changes' => 'Shrani spremembe',
      'Cancel' => 'Prekliči',
      'Please type your name' => 'Vnesite svoje ime',
      'Please type your e-mail address' => 'Vnesite svoj e-poštni naslov',
      'Basic details' => 'Osnovne podrobnosti',
      'Failed to save the changes!' => 'Sprememb ni bilo mogoče shraniti!',
      'No changes made' => 'Ni sprememb',
      'Change password' => 'Spremeni geslo',
      'Name' => 'Ime',
      'E-mail address' => 'Elektronski naslov',
      'E-mail notifications' => 'Obvestila na elektronski naslov',
      'Mute sound notifications' => 'Izklopite zvok obvestil',
      'Connected apps' => 'Povezane aplikacije',
      'Profile image' => 'Slika profila',
      'Phone' => 'Telefon',
    ),
    'File Upload' => 
    array (
      'File uploaded' => 'Datoteka naložena',
      'Failed to upload file' => 'Nalaganje datoteke ni uspelo',
      'Failed to create folder' => 'Mape ni bilo mogoče ustvariti',
      'Failed to upload file "%1": %2' => 'Nalaganje datoteke ni uspelo"%1": %2',
      'The monthly traffic limit has been reached!' => 'Mesečni promet je dosežen!',
      'No more file space available!' => 'Ni več prostora za datoteke!',
      'A file named "%1" already exists!' => 'Datoteka z imenom "%1" že obstaja!',
      'The file needs to be uploaded from the beginning.' => 'Datoteko je treba naložiti od začetka.',
      'Failed to transfer data. Make sure you are not trying to upload an empty folder.' => 'Prenos podatkov ni uspel. Prepričajte se, da ne želite naložiti prazne mape.',
      'You are not allowed to upload to this shared folder.' => 'Nalaganje v to mapo v skupni rabi ni dovoljeno.',
      'Failed to upload file part' => 'Datoteke ni bilo mogoče naložiti',
      'Failed to upload file. Please try again.' => 'Nalaganje datoteke ni uspelo. Prosim poskusite ponovno.',
    ),
    'Searching' => 
    array (
      'File name' => 'Ime datoteke',
      'File contents' => 'Vsebina datoteke',
      'Look in' => 'Poglej v',
      'Metadata Field' => 'Polje metapodatkov',
      'Metadata' => 'Metapodatki',
      'Select...' => 'Izberite ...',
      'Path' => 'Pot',
      'Searching...' => 'Iskanje ...',
      'Search' => 'Iskanje',
      '- None Selected -' => '- Nobeno izbrano -',
      'Metadata Type' => 'Vrsta metapodatkov',
      'Field Value' => 'Vrednost polja',
    ),
    'Custom Actions: Text Editor' => 
    array (
      'Text Editor' => 'Urejevalnik besedila',
      'Text File' => 'Beležnica',
      'Untitled.txt' => 'Brez naslova.txt',
      'Save' => 'Shrani',
      'Saving...' => 'Shranjevanje ...',
      'File successfully saved' => 'Datoteka je bila uspešno shranjena',
      'File successfully created' => 'Datoteka je bila uspešno ustvarjena',
      'A file with that name already exists' => 'Datoteka s tem imenom že obstaja',
      'Please type a file name' => 'Vnesite ime datoteke',
      'Other..' => 'Drugo ..',
      'New Text File.txt' => 'Nova beležnica.txt',
      'Would you like to reload the file using the selected charset? Any unsaved changes will be lost.' => 'Želite ponovno naložiti datoteko z izbranim naborom znakov? Vse neshranjene spremembe bodo izgubljene.',
      'Save and close' => 'Shrani in zapri',
      'Word wrap' => 'Obloga besed',
      'The file type is not allowed.' => 'Vrsta datoteke ni dovoljena.',
      'Close' => 'Zapri',
    ),
    'Labels' => 
    array (
      'APPROVED' => 'ODOBRENO',
      'PENDING' => 'V TEKU',
      'REJECTED' => 'ZAVRNJENO',
    ),
    'Custom Actions: MediaInfo' => 
    array (
      'Media Info' => 'Informacije',
    ),
    'Stars' => 
    array (
      'You are not allowed to set stars!' => 'Ni dovoljeno nastaviti zvezdic!',
      'No stars were added' => 'Ni dodanih zvezdic',
      'Star successfully added' => 'Zvezdica je bila uspešno dodana',
      '%1 stars successfully added' => 'Uspešno dodanih %1 zvezdic',
      'No stars were removed' => 'Nobena zvezdica ni bila odstranjena',
      'Star successfully removed' => 'Zvezdica je bila uspešno odstranjena',
      '%1 stars successfully removed' => '%1 zvezdic je bilo uspešno odstranjenih',
    ),
    'Custom Actions: Google Editor' => 
    array (
      'Read the <a href="%1" target="_blank">configuration guide</a>.' => 'Preberite <a href="%1" target="_blank">navodila za konfiguracijo</a>.',
      'Signing into Google...<br>Please check the opened popup for proceeding to the editor.' => 'Prijava v Google ... <br> Preverite odprto pojavno okno, da nadaljujete z urejevalnikom.',
      'Sending document data to Google...<br>Please wait.' => 'Pošiljanje datoteke k Googlu ... <br> Počakajte.',
      'Waiting for the editor to close...<br>If you close this window, your changes will not be saved to the document.' => 'Čakanje, da se urejevalnik zapre ... <br> Če zaprete to okno, spremembe ne bodo shranjene.',
      'Importing document from Google...' => 'Uvoz dokumenta iz Googla ...',
      'Blank file created successfully' => 'Prazna datoteka je bila uspešno ustvarjena',
      'Document with Google' => 'Dokument z Googlom',
    ),
    'Custom Actions: Audio Player' => 
    array (
      'Audio Player' => 'Avdio predvajalnik',
      'Select' => 'Izberite',
      'Loading audio player...' => 'Nalaganje predvajalnika zvoka ...',
      'Close player' => 'Zapri predvajalnik',
      'Previous' => 'Prejšnji',
      'Play/Pause' => 'Predvajaj / pavza',
      'Next' => 'Naslednji',
      'Shuffle' => 'Naključno predvajanje',
    ),
    'Custom Actions: Archive Explorer' => 
    array (
      'Archive Explorer' => 'Raziskovalec arhiva',
    ),
    'Custom Actions: Video Player' => 
    array (
      'Video Player' => 'Video predvajalnik',
    ),
    'Custom Actions: Image Viewer' => 
    array (
      'Image Viewer' => 'Pregledovalnik slik',
    ),
    'Custom Actions: Zamzar' => 
    array (
      'API key' => 'Ključ API',
    ),
    'Custom Actions: Google Earth' => 
    array (
      'Google Maps' => 'Google zemljevidi',
    ),
    'Custom Actions' => 
    array (
      'New tab' => 'Nov zavihek',
    ),
    'Custom Actions: Photo Proof Sheet' => 
    array (
      'Create photo proof sheet' => 'Ustvari Photo Proof Sheet',
      'Photo proof sheet successfully created in your home folder.' => 'Photo Proof Sheet je uspešno ustvarjen v vaši domači mapi.',
    ),
    'Custom Actions: Bing Maps' => 
    array (
      'Bing Maps API Key' => 'Bing Maps API ključ',
    ),
    'Admin: Guest Users' => 
    array (
      'Enable guest user accounts' => 'Omogoči gostujoče uporabniške račune',
    ),
    'Custom Actions: HTML Editor' => 
    array (
      'HTML Editor' => 'Urejevalnik HTML',
      'Save' => 'Shrani',
      'Save and close' => 'Shrani in zapri',
      'Close' => 'Zapri',
      'Unsaved changes' => 'Nespremenjene spremembe',
      'Discard the changes made?' => 'Zavrnite izvedene spremembe?',
    ),
  ),
);